Project:
  name: 'FNO'
  experiment: 'FNO'
  checkpoint: False
  save_top_k: 3
  erase: True
  do: 'train'
  devices: 1
  accelerator: 'gpu'
  save: False


data:
  train_num: 270
  valid_num: 30
  load_workers: 1
  frequency: 1
  batch: 10
  size: 61
  PATH: '/Users/dp/Documents/清华/FilterData/data'
  step: 10
model:
  name: "FNO"
  wavenumber: [30, 30, 30, 30,30,30,30]
  features: 20
  padding: 32
  with_grid: True
  loss: 'rel_l2'
  source_type: theta
  


  

train:
  batchsize: 10
  epochs: 100
  lr: 0.01
  step_size: 100
  gamma: 0.5
  weight_decay: 0.00001
  eta_min: 0.0005
  add_term: True




ckpt:
  PATH: "save_files"
  save_dir: 'FNO'
  alias: 'FNO'